<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/acquisition.php");
	include("$currDir/acquisition_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('acquisition');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "acquisition";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`acquisition`.`id`" => "id",
		"`acquisition`.`call_back`" => "call_back",
		"`acquisition`.`seller_name`" => "seller_name",
		"CONCAT_WS('-', LEFT(`acquisition`.`phone`,3), MID(`acquisition`.`phone`,4,3), RIGHT(`acquisition`.`phone`,4))" => "phone",
		"`acquisition`.`purchase_notes`" => "purchase_notes",
		"`acquisition`.`priority`" => "priority",
		"`acquisition`.`location_city`" => "location_city",
		"`acquisition`.`location_state`" => "location_state",
		"if(`acquisition`.`pickup_date`,date_format(`acquisition`.`pickup_date`,'%m/%d/%Y'),'')" => "pickup_date",
		"TIME_FORMAT(`acquisition`.`pickup_time`, '%r')" => "pickup_time",
		"`acquisition`.`street_address`" => "street_address",
		"`acquisition`.`category`" => "category",
		"`acquisition`.`ref_listing`" => "ref_listing",
		"`acquisition`.`photo_1`" => "photo_1",
		"`acquisition`.`photo_2`" => "photo_2",
		"`acquisition`.`photo_3`" => "photo_3",
		"`acquisition`.`photo_4`" => "photo_4",
		"`acquisition`.`photo_5`" => "photo_5",
		"`acquisition`.`photo_6`" => "photo_6"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`acquisition`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`acquisition`.`pickup_date`',
		10 => '`acquisition`.`pickup_time`',
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`acquisition`.`id`" => "id",
		"`acquisition`.`call_back`" => "call_back",
		"`acquisition`.`seller_name`" => "seller_name",
		"CONCAT_WS('-', LEFT(`acquisition`.`phone`,3), MID(`acquisition`.`phone`,4,3), RIGHT(`acquisition`.`phone`,4))" => "phone",
		"`acquisition`.`purchase_notes`" => "purchase_notes",
		"`acquisition`.`priority`" => "priority",
		"`acquisition`.`location_city`" => "location_city",
		"`acquisition`.`location_state`" => "location_state",
		"if(`acquisition`.`pickup_date`,date_format(`acquisition`.`pickup_date`,'%m/%d/%Y'),'')" => "pickup_date",
		"TIME_FORMAT(`acquisition`.`pickup_time`, '%r')" => "pickup_time",
		"`acquisition`.`street_address`" => "street_address",
		"`acquisition`.`category`" => "category",
		"`acquisition`.`ref_listing`" => "ref_listing",
		"`acquisition`.`photo_1`" => "photo_1",
		"`acquisition`.`photo_2`" => "photo_2",
		"`acquisition`.`photo_3`" => "photo_3",
		"`acquisition`.`photo_4`" => "photo_4",
		"`acquisition`.`photo_5`" => "photo_5",
		"`acquisition`.`photo_6`" => "photo_6"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`acquisition`.`id`" => "ID",
		"`acquisition`.`call_back`" => "Call back",
		"`acquisition`.`seller_name`" => "Seller name",
		"`acquisition`.`phone`" => "Phone",
		"`acquisition`.`purchase_notes`" => "Notepad & Item(s)",
		"`acquisition`.`priority`" => "Purchase Priority",
		"`acquisition`.`location_city`" => "City",
		"`acquisition`.`location_state`" => "State",
		"`acquisition`.`pickup_date`" => "Pickup date",
		"`acquisition`.`pickup_time`" => "Pickup time",
		"`acquisition`.`street_address`" => "Street address",
		"`acquisition`.`category`" => "Category",
		"`acquisition`.`ref_listing`" => "Link - Similar Online Product"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`acquisition`.`id`" => "id",
		"`acquisition`.`call_back`" => "call_back",
		"`acquisition`.`seller_name`" => "seller_name",
		"CONCAT_WS('-', LEFT(`acquisition`.`phone`,3), MID(`acquisition`.`phone`,4,3), RIGHT(`acquisition`.`phone`,4))" => "phone",
		"`acquisition`.`purchase_notes`" => "purchase_notes",
		"`acquisition`.`priority`" => "priority",
		"`acquisition`.`location_city`" => "location_city",
		"`acquisition`.`location_state`" => "location_state",
		"if(`acquisition`.`pickup_date`,date_format(`acquisition`.`pickup_date`,'%m/%d/%Y'),'')" => "pickup_date",
		"TIME_FORMAT(`acquisition`.`pickup_time`, '%r')" => "pickup_time",
		"`acquisition`.`street_address`" => "street_address",
		"`acquisition`.`category`" => "category",
		"`acquisition`.`ref_listing`" => "ref_listing"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`acquisition` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 183;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "acquisition_view.php";
	$x->RedirectAfterInsert = "acquisition_view.php?SelectedID=#ID#";
	$x->TableTitle = "Acquisition";
	$x->TableIcon = "resources/table_icons/client_account_template.png";
	$x->PrimaryKey = "`acquisition`.`id`";
	$x->DefaultSortField = '6';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 40, 86, 200, 35, 80, 150, 150, 150, 150);
	$x->ColCaption = array("Call back", "Seller name", "Phone", "Notepad & Item(s)", "Purchase Priority", "City", "Pickup date", "Pickup time", "Category", "Photo 1");
	$x->ColFieldName = array('call_back', 'seller_name', 'phone', 'purchase_notes', 'priority', 'location_city', 'pickup_date', 'pickup_time', 'category', 'photo_1');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 9, 10, 12, 14);

	$x->Template = 'templates/acquisition_templateTV.html';
	$x->SelectedTemplate = 'templates/acquisition_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `acquisition`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='acquisition' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `acquisition`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='acquisition' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`acquisition`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: acquisition_init
	$render=TRUE;
	if(function_exists('acquisition_init')){
		$args=array();
		$render=acquisition_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: acquisition_header
	$headerCode='';
	if(function_exists('acquisition_header')){
		$args=array();
		$headerCode=acquisition_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: acquisition_footer
	$footerCode='';
	if(function_exists('acquisition_footer')){
		$args=array();
		$footerCode=acquisition_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>