<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/employees.php");
	include("$currDir/employees_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('employees');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "employees";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`employees`.`id`" => "id",
		"`employees`.`first`" => "first",
		"`employees`.`last`" => "last",
		"`employees`.`street_addr`" => "street_addr",
		"`employees`.`city`" => "city",
		"`employees`.`state`" => "state",
		"if(`employees`.`hire_date`,date_format(`employees`.`hire_date`,'%m/%d/%Y'),'')" => "hire_date",
		"`employees`.`notes`" => "notes",
		"`employees`.`last_update`" => "last_update"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`employees`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`employees`.`hire_date`',
		8 => 8,
		9 => 9
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`employees`.`id`" => "id",
		"`employees`.`first`" => "first",
		"`employees`.`last`" => "last",
		"`employees`.`street_addr`" => "street_addr",
		"`employees`.`city`" => "city",
		"`employees`.`state`" => "state",
		"if(`employees`.`hire_date`,date_format(`employees`.`hire_date`,'%m/%d/%Y'),'')" => "hire_date",
		"`employees`.`notes`" => "notes",
		"`employees`.`last_update`" => "last_update"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`employees`.`id`" => "ID",
		"`employees`.`first`" => "First name",
		"`employees`.`last`" => "Last name",
		"`employees`.`street_addr`" => "Street address",
		"`employees`.`city`" => "City",
		"`employees`.`state`" => "State",
		"`employees`.`hire_date`" => "Since",
		"`employees`.`notes`" => "Notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`employees`.`id`" => "id",
		"`employees`.`first`" => "first",
		"`employees`.`last`" => "last",
		"`employees`.`street_addr`" => "street_addr",
		"`employees`.`city`" => "city",
		"`employees`.`state`" => "state",
		"if(`employees`.`hire_date`,date_format(`employees`.`hire_date`,'%m/%d/%Y'),'')" => "hire_date",
		"`employees`.`notes`" => "notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`employees` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "employees_view.php";
	$x->RedirectAfterInsert = "employees_view.php?SelectedID=#ID#";
	$x->TableTitle = "Employees";
	$x->TableIcon = "resources/table_icons/ceo.png";
	$x->PrimaryKey = "`employees`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("First name", "Last name", "Street address", "City", "State", "Since");
	$x->ColFieldName = array('first', 'last', 'street_addr', 'city', 'state', 'hire_date');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	$x->Template = 'templates/employees_templateTV.html';
	$x->SelectedTemplate = 'templates/employees_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `employees`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='employees' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `employees`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='employees' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`employees`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: employees_init
	$render=TRUE;
	if(function_exists('employees_init')){
		$args=array();
		$render=employees_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: employees_header
	$headerCode='';
	if(function_exists('employees_header')){
		$args=array();
		$headerCode=employees_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: employees_footer
	$footerCode='';
	if(function_exists('employees_footer')){
		$args=array();
		$footerCode=employees_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>