<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/expenses.php");
	include("$currDir/expenses_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('expenses');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "expenses";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`expenses`.`id`" => "id",
		"`expenses`.`category`" => "category",
		"`expenses`.`account`" => "account",
		"CONCAT('$', FORMAT(`expenses`.`price`, 2))" => "price",
		"`expenses`.`decription`" => "decription",
		"if(`expenses`.`date`,date_format(`expenses`.`date`,'%m/%d/%Y'),'')" => "date",
		"`expenses`.`from_account`" => "from_account",
		"`expenses`.`account_detail`" => "account_detail",
		"`expenses`.`check_number`" => "check_number",
		"`expenses`.`photo`" => "photo"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`expenses`.`id`',
		2 => 2,
		3 => 3,
		4 => '`expenses`.`price`',
		5 => 5,
		6 => '`expenses`.`date`',
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`expenses`.`id`" => "id",
		"`expenses`.`category`" => "category",
		"`expenses`.`account`" => "account",
		"CONCAT('$', FORMAT(`expenses`.`price`, 2))" => "price",
		"`expenses`.`decription`" => "decription",
		"if(`expenses`.`date`,date_format(`expenses`.`date`,'%m/%d/%Y'),'')" => "date",
		"`expenses`.`from_account`" => "from_account",
		"`expenses`.`account_detail`" => "account_detail",
		"`expenses`.`check_number`" => "check_number",
		"`expenses`.`photo`" => "photo"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`expenses`.`id`" => "ID",
		"`expenses`.`category`" => "Category",
		"`expenses`.`account`" => "Account / Person",
		"`expenses`.`price`" => "Money",
		"`expenses`.`decription`" => "Decription",
		"`expenses`.`date`" => "Date",
		"`expenses`.`from_account`" => "Account - Paid from",
		"`expenses`.`account_detail`" => "Check / Card",
		"`expenses`.`check_number`" => "Check # or Last 4 digits of Card"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`expenses`.`id`" => "id",
		"`expenses`.`category`" => "category",
		"`expenses`.`account`" => "account",
		"CONCAT('$', FORMAT(`expenses`.`price`, 2))" => "price",
		"`expenses`.`decription`" => "decription",
		"if(`expenses`.`date`,date_format(`expenses`.`date`,'%m/%d/%Y'),'')" => "date",
		"`expenses`.`from_account`" => "from_account",
		"`expenses`.`account_detail`" => "account_detail",
		"`expenses`.`check_number`" => "check_number"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`expenses` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "expenses_view.php";
	$x->RedirectAfterInsert = "expenses_view.php?SelectedID=#ID#";
	$x->TableTitle = "Expenses";
	$x->TableIcon = "resources/table_icons/credit.png";
	$x->PrimaryKey = "`expenses`.`id`";

	$x->ColWidth   = array(  150, 150, 80, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Category", "Account / Person", "Money", "Decription", "Date", "Account - Paid from", "Check / Card", "Check # or Last 4 digits of Card", "Receipt Photo");
	$x->ColFieldName = array('category', 'account', 'price', 'decription', 'date', 'from_account', 'account_detail', 'check_number', 'photo');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	$x->Template = 'templates/expenses_templateTV.html';
	$x->SelectedTemplate = 'templates/expenses_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `expenses`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='expenses' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `expenses`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='expenses' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`expenses`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: expenses_init
	$render=TRUE;
	if(function_exists('expenses_init')){
		$args=array();
		$render=expenses_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: expenses_header
	$headerCode='';
	if(function_exists('expenses_header')){
		$args=array();
		$headerCode=expenses_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: expenses_footer
	$footerCode='';
	if(function_exists('expenses_footer')){
		$args=array();
		$footerCode=expenses_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>