<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/inventory.php");
	include("$currDir/inventory_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('inventory');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "inventory";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`inventory`.`id`" => "id",
		"`inventory`.`item`" => "item",
		"`inventory`.`status`" => "status",
		"`inventory`.`description`" => "description",
		"`inventory`.`item_cost`" => "item_cost",
		"CONCAT('$', FORMAT(`inventory`.`price_high`, 2))" => "price_high",
		"CONCAT('$', FORMAT(`inventory`.`price_low`, 2))" => "price_low",
		"`inventory`.`item_number`" => "item_number",
		"`inventory`.`ref_listing`" => "ref_listing",
		"`inventory`.`inventory_photo`" => "inventory_photo",
		"`inventory`.`last_update`" => "last_update",
		"`inventory`.`location`" => "location"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`inventory`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`inventory`.`item_cost`',
		6 => '`inventory`.`price_high`',
		7 => '`inventory`.`price_low`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`inventory`.`location`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`inventory`.`id`" => "id",
		"`inventory`.`item`" => "item",
		"`inventory`.`status`" => "status",
		"`inventory`.`description`" => "description",
		"`inventory`.`item_cost`" => "item_cost",
		"CONCAT('$', FORMAT(`inventory`.`price_high`, 2))" => "price_high",
		"CONCAT('$', FORMAT(`inventory`.`price_low`, 2))" => "price_low",
		"`inventory`.`item_number`" => "item_number",
		"`inventory`.`ref_listing`" => "ref_listing",
		"`inventory`.`inventory_photo`" => "inventory_photo",
		"`inventory`.`last_update`" => "last_update",
		"`inventory`.`location`" => "location"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`inventory`.`id`" => "ID",
		"`inventory`.`item`" => "Item",
		"`inventory`.`status`" => "Status",
		"`inventory`.`item_cost`" => "Cost to Acquire",
		"`inventory`.`price_high`" => "Price High",
		"`inventory`.`price_low`" => "Price Low",
		"`inventory`.`item_number`" => "Listing ID",
		"`inventory`.`ref_listing`" => "Link - Similar Online Product",
		"`inventory`.`location`" => "Location - Shelf ID"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`inventory`.`id`" => "id",
		"`inventory`.`item`" => "item",
		"`inventory`.`status`" => "status",
		"`inventory`.`item_cost`" => "item_cost",
		"CONCAT('$', FORMAT(`inventory`.`price_high`, 2))" => "price_high",
		"CONCAT('$', FORMAT(`inventory`.`price_low`, 2))" => "price_low",
		"`inventory`.`item_number`" => "item_number",
		"`inventory`.`ref_listing`" => "ref_listing",
		"`inventory`.`location`" => "location"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`inventory` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "inventory_view.php";
	$x->RedirectAfterInsert = "inventory_view.php?SelectedID=#ID#";
	$x->TableTitle = "Inventory";
	$x->TableIcon = "resources/table_icons/attributes_display.png";
	$x->PrimaryKey = "`inventory`.`id`";
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 80, 70, 70, 150, 150, 150);
	$x->ColCaption = array("ID", "Item", "Status", "Cost to Acquire", "Price High", "Price Low", "Listing ID", "Distinguishing photo", "Location - Shelf ID");
	$x->ColFieldName = array('id', 'item', 'status', 'item_cost', 'price_high', 'price_low', 'item_number', 'inventory_photo', 'location');
	$x->ColNumber  = array(1, 2, 3, 5, 6, 7, 8, 10, 12);

	$x->Template = 'templates/inventory_templateTV.html';
	$x->SelectedTemplate = 'templates/inventory_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `inventory`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='inventory' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `inventory`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='inventory' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`inventory`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: inventory_init
	$render=TRUE;
	if(function_exists('inventory_init')){
		$args=array();
		$render=inventory_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `inventory`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery="select CONCAT('$', FORMAT(sum(`inventory`.`price_low`), 2)) from ".$x->QueryFrom.' '.$QueryWhere;
		$res=sql($sumQuery, $eo);
		if($row=db_fetch_row($res)){
			$sumRow ="<tr class=\"success\">";
			if(!isset($_REQUEST['Print_x'])) $sumRow.="<td class=\"text-center\"><strong>&sum;</strong></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td class=\"text-right\">{$row[0]}</td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td></td>";
			$sumRow.="</tr>";

			$x->HTML=str_replace("<!-- tv data below -->", '', $x->HTML);
			$x->HTML=str_replace("<!-- tv data above -->", $sumRow, $x->HTML);
		}
	}

	// hook: inventory_header
	$headerCode='';
	if(function_exists('inventory_header')){
		$args=array();
		$headerCode=inventory_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: inventory_footer
	$footerCode='';
	if(function_exists('inventory_footer')){
		$args=array();
		$footerCode=inventory_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>