<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/register_items.php");
	include("$currDir/register_items_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('register_items');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "register_items";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`register_items`.`id`" => "id",
		"IF(    CHAR_LENGTH(`register1`.`id`), CONCAT_WS('',   `register1`.`id`), '') /* Orders */" => "previous_order",
		"IF(    CHAR_LENGTH(`inventory1`.`item`), CONCAT_WS('',   `inventory1`.`item`), '') /* Item name */" => "item_name",
		"IF(    CHAR_LENGTH(`inventory1`.`price_high`), CONCAT_WS('',   `inventory1`.`price_high`), '') /* Cost */" => "cost",
		"IF(    CHAR_LENGTH(`inventory1`.`inventory_photo`), CONCAT_WS('',   `inventory1`.`inventory_photo`), '') /* Image */" => "ref_img"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`register_items`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`register_items`.`id`" => "id",
		"IF(    CHAR_LENGTH(`register1`.`id`), CONCAT_WS('',   `register1`.`id`), '') /* Orders */" => "previous_order",
		"IF(    CHAR_LENGTH(`inventory1`.`item`), CONCAT_WS('',   `inventory1`.`item`), '') /* Item name */" => "item_name",
		"IF(    CHAR_LENGTH(`inventory1`.`price_high`), CONCAT_WS('',   `inventory1`.`price_high`), '') /* Cost */" => "cost",
		"IF(    CHAR_LENGTH(`inventory1`.`inventory_photo`), CONCAT_WS('',   `inventory1`.`inventory_photo`), '') /* Image */" => "ref_img"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`register_items`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`register1`.`id`), CONCAT_WS('',   `register1`.`id`), '') /* Orders */" => "Orders",
		"IF(    CHAR_LENGTH(`inventory1`.`item`), CONCAT_WS('',   `inventory1`.`item`), '') /* Item name */" => "Item name",
		"IF(    CHAR_LENGTH(`inventory1`.`price_high`), CONCAT_WS('',   `inventory1`.`price_high`), '') /* Cost */" => "Cost",
		"IF(    CHAR_LENGTH(`inventory1`.`inventory_photo`), CONCAT_WS('',   `inventory1`.`inventory_photo`), '') /* Image */" => "Image"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`register_items`.`id`" => "id",
		"IF(    CHAR_LENGTH(`register1`.`id`), CONCAT_WS('',   `register1`.`id`), '') /* Orders */" => "previous_order",
		"IF(    CHAR_LENGTH(`inventory1`.`item`), CONCAT_WS('',   `inventory1`.`item`), '') /* Item name */" => "item_name",
		"IF(    CHAR_LENGTH(`inventory1`.`price_high`), CONCAT_WS('',   `inventory1`.`price_high`), '') /* Cost */" => "cost",
		"IF(    CHAR_LENGTH(`inventory1`.`inventory_photo`), CONCAT_WS('',   `inventory1`.`inventory_photo`), '') /* Image */" => "ref_img"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'previous_order' => 'Orders', 'item_name' => 'Item name');

	$x->QueryFrom="`register_items` LEFT JOIN `register` as register1 ON `register1`.`id`=`register_items`.`previous_order` LEFT JOIN `inventory` as inventory1 ON `inventory1`.`id`=`register_items`.`item_name` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 0;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "register_items_view.php";
	$x->RedirectAfterInsert = "register_items_view.php?SelectedID=#ID#";
	$x->TableTitle = "Order Items";
	$x->TableIcon = "resources/table_icons/application_form_magnify.png";
	$x->PrimaryKey = "`register_items`.`id`";

	$x->ColWidth   = array(  150, 80, 150);
	$x->ColCaption = array("Item name", "Cost", "Image");
	$x->ColFieldName = array('item_name', 'cost', 'ref_img');
	$x->ColNumber  = array(3, 4, 5);

	$x->Template = 'templates/register_items_templateTV.html';
	$x->SelectedTemplate = 'templates/register_items_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `register_items`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='register_items' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `register_items`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='register_items' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`register_items`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: register_items_init
	$render=TRUE;
	if(function_exists('register_items_init')){
		$args=array();
		$render=register_items_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `register_items`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery="select sum(`register_items`.`cost`) from ".$x->QueryFrom.' '.$QueryWhere;
		$res=sql($sumQuery, $eo);
		if($row=db_fetch_row($res)){
			$sumRow ="<tr class=\"success\">";
			if(!isset($_REQUEST['Print_x'])) $sumRow.="<td class=\"text-center\"><strong>&sum;</strong></td>";
			$sumRow.="<td></td>";
			$sumRow.="<td class=\"text-right\">{$row[0]}</td>";
			$sumRow.="<td></td>";
			$sumRow.="</tr>";

			$x->HTML=str_replace("<!-- tv data below -->", '', $x->HTML);
			$x->HTML=str_replace("<!-- tv data above -->", $sumRow, $x->HTML);
		}
	}

	// hook: register_items_header
	$headerCode='';
	if(function_exists('register_items_header')){
		$args=array();
		$headerCode=register_items_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: register_items_footer
	$footerCode='';
	if(function_exists('register_items_footer')){
		$args=array();
		$footerCode=register_items_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>