<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header("Content-type: text/javascript; charset=UTF-8");

	if(!get_sql_from('register_items')){ die('// Access denied!'); }

	$mfk=$_GET['mfk'];
	$id=makeSafe($_GET['id']);
	$rnd1=intval($_GET['rnd1']); if(!$rnd1) $rnd1='';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'item_name':
			if(!$id){
				?>
				$('cost<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				$('ref_img<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				<?php
				break;
			}
			$res = sql("SELECT `inventory`.`id` as 'id', `inventory`.`item` as 'item', `inventory`.`status` as 'status', `inventory`.`description` as 'description', `inventory`.`item_cost` as 'item_cost', CONCAT('$', FORMAT(`inventory`.`price_high`, 2)) as 'price_high', CONCAT('$', FORMAT(`inventory`.`price_low`, 2)) as 'price_low', `inventory`.`item_number` as 'item_number', `inventory`.`ref_listing` as 'ref_listing', `inventory`.`inventory_photo` as 'inventory_photo', `inventory`.`last_update` as 'last_update', `inventory`.`location` as 'location' FROM `inventory`  WHERE `inventory`.`id`='$id' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#cost<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['price_high']))); ?>&nbsp;');
			<?php if($row['inventory_photo']){ ?> 
				$j('#ref_img<?php echo $rnd1; ?>').html('<a href="<?php echo $Translation['ImageFolder'] . addslashes(str_replace(array("\r", "\n"), '', $row['inventory_photo'])); ?>" data-lightbox="register_items_dv"><img src="thumbnail.php?i=<?php echo urlencode($row['inventory_photo']); ?>&t=inventory&f=inventory_photo&v=dv" class="img-thumbnail"></a>');
			<?php }else{ ?>
				$j('#ref_img<?php echo $rnd1; ?>').html('<img src="thumbnail.php?i=&t=inventory&f=inventory_photo&v=dv" class="img-thumbnail">');
			<?php } ?>
			<?php
			break;


	}

?>