<?php

// Data functions (insert, update, delete, form) for table register_items

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function register_items_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('register_items');
	if(!$arrPerm[1]){
		return false;
	}

	$data['previous_order'] = makeSafe($_REQUEST['previous_order']);
		if($data['previous_order'] == empty_lookup_value){ $data['previous_order'] = ''; }
	$data['item_name'] = makeSafe($_REQUEST['item_name']);
		if($data['item_name'] == empty_lookup_value){ $data['item_name'] = ''; }
	$data['cost'] = makeSafe($_REQUEST['item_name']);
		if($data['cost'] == empty_lookup_value){ $data['cost'] = ''; }
	$data['ref_img'] = makeSafe($_REQUEST['item_name']);
		if($data['ref_img'] == empty_lookup_value){ $data['ref_img'] = ''; }
	if($data['cost'] == '') $data['cost'] = "0.00";

	// hook: register_items_before_insert
	if(function_exists('register_items_before_insert')){
		$args=array();
		if(!register_items_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `register_items` set       `item_name`=' . (($data['item_name'] !== '' && $data['item_name'] !== NULL) ? "'{$data['item_name']}'" : 'NULL') . ', `cost`=' . (($data['cost'] !== '' && $data['cost'] !== NULL) ? "'{$data['cost']}'" : 'NULL') . ', `ref_img`=' . (($data['ref_img'] !== '' && $data['ref_img'] !== NULL) ? "'{$data['ref_img']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"register_items_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic previous_order
	if($_REQUEST['filterer_previous_order']){
		sql("update `register_items` set `previous_order`='" . makeSafe($_REQUEST['filterer_previous_order']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: register_items_after_insert
	if(function_exists('register_items_after_insert')){
		$res = sql("select * from `register_items` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!register_items_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='register_items', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function register_items_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('register_items');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='register_items' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='register_items' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: register_items_before_delete
	if(function_exists('register_items_before_delete')){
		$args=array();
		if(!register_items_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `register_items` where `id`='$selected_id'", $eo);

	// hook: register_items_after_delete
	if(function_exists('register_items_after_delete')){
		$args=array();
		register_items_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='register_items' and pkValue='$selected_id'", $eo);
}

function register_items_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('register_items');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='register_items' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='register_items' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['previous_order'] = makeSafe($_REQUEST['previous_order']);
		if($data['previous_order'] == empty_lookup_value){ $data['previous_order'] = ''; }
	$data['item_name'] = makeSafe($_REQUEST['item_name']);
		if($data['item_name'] == empty_lookup_value){ $data['item_name'] = ''; }
	$data['cost'] = makeSafe($_REQUEST['item_name']);
		if($data['cost'] == empty_lookup_value){ $data['cost'] = ''; }
	$data['ref_img'] = makeSafe($_REQUEST['item_name']);
		if($data['ref_img'] == empty_lookup_value){ $data['ref_img'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: register_items_before_update
	if(function_exists('register_items_before_update')){
		$args=array();
		if(!register_items_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `register_items` set       `item_name`=' . (($data['item_name'] !== '' && $data['item_name'] !== NULL) ? "'{$data['item_name']}'" : 'NULL') . ', `cost`=' . (($data['cost'] !== '' && $data['cost'] !== NULL) ? "'{$data['cost']}'" : 'NULL') . ', `ref_img`=' . (($data['ref_img'] !== '' && $data['ref_img'] !== NULL) ? "'{$data['ref_img']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="register_items_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: register_items_after_update
	if(function_exists('register_items_after_update')){
		$res = sql("SELECT * FROM `register_items` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!register_items_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='register_items' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function register_items_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('register_items');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_previous_order = thisOr(undo_magic_quotes($_REQUEST['filterer_previous_order']), '');
	$filterer_item_name = thisOr(undo_magic_quotes($_REQUEST['filterer_item_name']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: previous_order
	$combo_previous_order = new DataCombo;
	// combobox: item_name
	$combo_item_name = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='register_items' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='register_items' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `register_items` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_previous_order->SelectedData = $row['previous_order'];
		$combo_item_name->SelectedData = $row['item_name'];
	}else{
		$combo_previous_order->SelectedData = $filterer_previous_order;
		$combo_item_name->SelectedData = $filterer_item_name;
	}
	$combo_previous_order->HTML = '<span id="previous_order-container' . $rnd1 . '"></span><input type="hidden" name="previous_order" id="previous_order' . $rnd1 . '" value="' . html_attr($combo_previous_order->SelectedData) . '">';
	$combo_previous_order->MatchText = '<span id="previous_order-container-readonly' . $rnd1 . '"></span><input type="hidden" name="previous_order" id="previous_order' . $rnd1 . '" value="' . html_attr($combo_previous_order->SelectedData) . '">';
	$combo_item_name->HTML = '<span id="item_name-container' . $rnd1 . '"></span><input type="hidden" name="item_name" id="item_name' . $rnd1 . '" value="' . html_attr($combo_item_name->SelectedData) . '">';
	$combo_item_name->MatchText = '<span id="item_name-container-readonly' . $rnd1 . '"></span><input type="hidden" name="item_name" id="item_name' . $rnd1 . '" value="' . html_attr($combo_item_name->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_previous_order__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['previous_order'] : $filterer_previous_order); ?>"};
		var current_item_name__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['item_name'] : $filterer_item_name); ?>"};

		jQuery(function() {
			if(typeof(previous_order_reload__RAND__) == 'function') previous_order_reload__RAND__();
			if(typeof(item_name_reload__RAND__) == 'function') item_name_reload__RAND__();
		});
		function previous_order_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#previous_order-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_previous_order__RAND__.value, t: 'register_items', f: 'previous_order' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						$j('[name="previous_order"]').val(resp.results[0].id);
						$j('[id=previous_order-container-readonly__RAND__]').html('<span id="previous_order-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }


						if(typeof(previous_order_update_autofills__RAND__) == 'function') previous_order_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 99) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'register_items', f: 'previous_order' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_previous_order__RAND__.value = e.added.id;
				current_previous_order__RAND__.text = e.added.text;
				$j('[name="previous_order"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }


				if(typeof(previous_order_update_autofills__RAND__) == 'function') previous_order_update_autofills__RAND__();
			});

			if(!$j("#previous_order-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_previous_order__RAND__.value, t: 'register_items', f: 'previous_order' }
				}).done(function(resp){
					$j('[name="previous_order"]').val(resp.results[0].id);
					$j('[id=previous_order-container-readonly__RAND__]').html('<span id="previous_order-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }

					if(typeof(previous_order_update_autofills__RAND__) == 'function') previous_order_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_previous_order__RAND__.value, t: 'register_items', f: 'previous_order' }
			}).done(function(resp){
				$j('[id=previous_order-container__RAND__], [id=previous_order-container-readonly__RAND__]').html('<span id="previous_order-match-text">' + resp.results[0].text + '</span>');
				if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }

				if(typeof(previous_order_update_autofills__RAND__) == 'function') previous_order_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function item_name_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#item_name-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_item_name__RAND__.value, t: 'register_items', f: 'item_name' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						$j('[name="item_name"]').val(resp.results[0].id);
						$j('[id=item_name-container-readonly__RAND__]').html('<span id="item_name-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=inventory_view_parent]').hide(); }else{ $j('.btn[id=inventory_view_parent]').show(); }


						if(typeof(item_name_update_autofills__RAND__) == 'function') item_name_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 99) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'register_items', f: 'item_name' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_item_name__RAND__.value = e.added.id;
				current_item_name__RAND__.text = e.added.text;
				$j('[name="item_name"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=inventory_view_parent]').hide(); }else{ $j('.btn[id=inventory_view_parent]').show(); }


				if(typeof(item_name_update_autofills__RAND__) == 'function') item_name_update_autofills__RAND__();
			});

			if(!$j("#item_name-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_item_name__RAND__.value, t: 'register_items', f: 'item_name' }
				}).done(function(resp){
					$j('[name="item_name"]').val(resp.results[0].id);
					$j('[id=item_name-container-readonly__RAND__]').html('<span id="item_name-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=inventory_view_parent]').hide(); }else{ $j('.btn[id=inventory_view_parent]').show(); }

					if(typeof(item_name_update_autofills__RAND__) == 'function') item_name_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_item_name__RAND__.value, t: 'register_items', f: 'item_name' }
			}).done(function(resp){
				$j('[id=item_name-container__RAND__], [id=item_name-container-readonly__RAND__]').html('<span id="item_name-match-text">' + resp.results[0].text + '</span>');
				if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=inventory_view_parent]').hide(); }else{ $j('.btn[id=inventory_view_parent]').show(); }

				if(typeof(item_name_update_autofills__RAND__) == 'function') item_name_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/register_items_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/register_items_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Inventory order details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return register_items_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return register_items_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return register_items_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#item_name').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#item_name_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(previous_order)%%>', $combo_previous_order->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(previous_order)%%>', $combo_previous_order->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(previous_order)%%>', urlencode($combo_previous_order->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(item_name)%%>', $combo_item_name->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(item_name)%%>', $combo_item_name->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(item_name)%%>', urlencode($combo_item_name->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'previous_order' => array('register', 'Orders'), 'item_name' => array('inventory', 'Item name'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(previous_order)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(item_name)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(previous_order)%%>', html_attr($row['previous_order']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(previous_order)%%>', urlencode($urow['previous_order']), $templateCode);
		$templateCode=str_replace('<%%VALUE(item_name)%%>', html_attr($row['item_name']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(item_name)%%>', urlencode($urow['item_name']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(previous_order)%%>', ( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_previous_order->SelectedData : ''), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(previous_order)%%>', urlencode( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_previous_order->SelectedData : ''), $templateCode);
		$templateCode=str_replace('<%%VALUE(item_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(item_name)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode.="\titem_name_update_autofills$rnd1 = function(){\n";
	$templateCode.="\t\tnew Ajax.Request(\n";
	if($dvprint){
		$templateCode.="\t\t\t'register_items_autofill.php?rnd1=$rnd1&mfk=item_name&id=' + encodeURIComponent('".addslashes($row['item_name'])."'),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get'}\n";
	}else{
		$templateCode.="\t\t\t'register_items_autofill.php?rnd1=$rnd1&mfk=item_name&id=' + encodeURIComponent(current_item_name{$rnd1}.value),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get', onCreate: function(){ \$j('#item_name$rnd1').prop('disabled', true); \$j('#item_nameLoading').html('<img src=loading.gif align=top>'); }, onComplete: function(){".(($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#item_name$rnd1').prop('disabled', false); " : "\$j('#item_name$rnd1').prop('disabled', true); ")."\$j('#item_nameLoading').html('');}}\n";
	}
	$templateCode.="\t\t);\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$j('#item_name_caption').length) \$j('#item_name_caption').click(function(){ item_name_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: register_items_dv
	if(function_exists('register_items_dv')){
		$args=array();
		register_items_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>