<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header("Content-type: text/javascript; charset=UTF-8");

	if(!get_sql_from('shipping')){ die('// Access denied!'); }

	$mfk=$_GET['mfk'];
	$id=makeSafe($_GET['id']);
	$rnd1=intval($_GET['rnd1']); if(!$rnd1) $rnd1='';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'register_id':
			if(!$id){
				?>
				$('client_name<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				$('phone<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				$('email<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				<?php
				break;
			}
			$res = sql("SELECT `register`.`id` as 'id', `register`.`client_name` as 'client_name', IF(    CHAR_LENGTH(`employees1`.`first`) || CHAR_LENGTH(`employees1`.`last`), CONCAT_WS('',   `employees1`.`first`, ' ', `employees1`.`last`), '') as 'seller', `register`.`date` as 'date', `register`.`phone` as 'phone', `register`.`email` as 'email' FROM `register` LEFT JOIN `employees` as employees1 ON `employees1`.`id`=`register`.`seller`  WHERE `register`.`id`='$id' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#client_name<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['client_name']))); ?>&nbsp;');
			$j('#phone<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['phone']))); ?>&nbsp;');
			$j('#email<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['email']))); ?>&nbsp;');
			<?php
			break;


	}

?>