<?php

// Data functions (insert, update, delete, form) for table shipping

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function shipping_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('shipping');
	if(!$arrPerm[1]){
		return false;
	}

	$data['register_id'] = makeSafe($_REQUEST['register_id']);
		if($data['register_id'] == empty_lookup_value){ $data['register_id'] = ''; }
	$data['client_name'] = makeSafe($_REQUEST['register_id']);
		if($data['client_name'] == empty_lookup_value){ $data['client_name'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['register_id']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['email'] = makeSafe($_REQUEST['register_id']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['company'] = makeSafe($_REQUEST['company']);
		if($data['company'] == empty_lookup_value){ $data['company'] = ''; }
	$data['shipping_gateway'] = makeSafe($_REQUEST['shipping_gateway']);
		if($data['shipping_gateway'] == empty_lookup_value){ $data['shipping_gateway'] = ''; }
	$data['street_address'] = makeSafe($_REQUEST['street_address']);
		if($data['street_address'] == empty_lookup_value){ $data['street_address'] = ''; }
	$data['city'] = makeSafe($_REQUEST['city']);
		if($data['city'] == empty_lookup_value){ $data['city'] = ''; }
	$data['state'] = makeSafe($_REQUEST['state']);
		if($data['state'] == empty_lookup_value){ $data['state'] = ''; }
	$data['zip'] = makeSafe($_REQUEST['zip']);
		if($data['zip'] == empty_lookup_value){ $data['zip'] = ''; }
	$data['country'] = makeSafe($_REQUEST['country']);
		if($data['country'] == empty_lookup_value){ $data['country'] = ''; }
	$data['ship_width'] = makeSafe($_REQUEST['ship_width']);
		if($data['ship_width'] == empty_lookup_value){ $data['ship_width'] = ''; }
	$data['ship_length'] = makeSafe($_REQUEST['ship_length']);
		if($data['ship_length'] == empty_lookup_value){ $data['ship_length'] = ''; }
	$data['ship_height'] = makeSafe($_REQUEST['ship_height']);
		if($data['ship_height'] == empty_lookup_value){ $data['ship_height'] = ''; }
	$data['distance_unit'] = makeSafe($_REQUEST['distance_unit']);
		if($data['distance_unit'] == empty_lookup_value){ $data['distance_unit'] = ''; }
	$data['ship_weight'] = makeSafe($_REQUEST['ship_weight']);
		if($data['ship_weight'] == empty_lookup_value){ $data['ship_weight'] = ''; }
	if($data['shipping_gateway']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Shipper': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['street_address']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Street address': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['city']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'City': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['state']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'State': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['zip']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Zip': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['country']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Country': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['ship_mass_unit'] == '') $data['ship_mass_unit'] = "lb";

	// hook: shipping_before_insert
	if(function_exists('shipping_before_insert')){
		$args=array();
		if(!shipping_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `shipping` set       `register_id`=' . (($data['register_id'] !== '' && $data['register_id'] !== NULL) ? "'{$data['register_id']}'" : 'NULL') . ', `client_name`=' . (($data['client_name'] !== '' && $data['client_name'] !== NULL) ? "'{$data['client_name']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `company`=' . (($data['company'] !== '' && $data['company'] !== NULL) ? "'{$data['company']}'" : 'NULL') . ', `shipping_gateway`=' . (($data['shipping_gateway'] !== '' && $data['shipping_gateway'] !== NULL) ? "'{$data['shipping_gateway']}'" : 'NULL') . ', `street_address`=' . (($data['street_address'] !== '' && $data['street_address'] !== NULL) ? "'{$data['street_address']}'" : 'NULL') . ', `city`=' . (($data['city'] !== '' && $data['city'] !== NULL) ? "'{$data['city']}'" : 'NULL') . ', `state`=' . (($data['state'] !== '' && $data['state'] !== NULL) ? "'{$data['state']}'" : 'NULL') . ', `zip`=' . (($data['zip'] !== '' && $data['zip'] !== NULL) ? "'{$data['zip']}'" : 'NULL') . ', `country`=' . (($data['country'] !== '' && $data['country'] !== NULL) ? "'{$data['country']}'" : 'NULL') . ', `ship_width`=' . (($data['ship_width'] !== '' && $data['ship_width'] !== NULL) ? "'{$data['ship_width']}'" : 'NULL') . ', `ship_length`=' . (($data['ship_length'] !== '' && $data['ship_length'] !== NULL) ? "'{$data['ship_length']}'" : 'NULL') . ', `ship_height`=' . (($data['ship_height'] !== '' && $data['ship_height'] !== NULL) ? "'{$data['ship_height']}'" : 'NULL') . ', `distance_unit`=' . (($data['distance_unit'] !== '' && $data['distance_unit'] !== NULL) ? "'{$data['distance_unit']}'" : 'NULL') . ', `ship_weight`=' . (($data['ship_weight'] !== '' && $data['ship_weight'] !== NULL) ? "'{$data['ship_weight']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"shipping_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: shipping_after_insert
	if(function_exists('shipping_after_insert')){
		$res = sql("select * from `shipping` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!shipping_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='shipping', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function shipping_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('shipping');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='shipping' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='shipping' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: shipping_before_delete
	if(function_exists('shipping_before_delete')){
		$args=array();
		if(!shipping_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `shipping` where `id`='$selected_id'", $eo);

	// hook: shipping_after_delete
	if(function_exists('shipping_after_delete')){
		$args=array();
		shipping_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='shipping' and pkValue='$selected_id'", $eo);
}

function shipping_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('shipping');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='shipping' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='shipping' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['register_id'] = makeSafe($_REQUEST['register_id']);
		if($data['register_id'] == empty_lookup_value){ $data['register_id'] = ''; }
	$data['client_name'] = makeSafe($_REQUEST['register_id']);
		if($data['client_name'] == empty_lookup_value){ $data['client_name'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['register_id']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['email'] = makeSafe($_REQUEST['register_id']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['company'] = makeSafe($_REQUEST['company']);
		if($data['company'] == empty_lookup_value){ $data['company'] = ''; }
	$data['shipping_gateway'] = makeSafe($_REQUEST['shipping_gateway']);
		if($data['shipping_gateway'] == empty_lookup_value){ $data['shipping_gateway'] = ''; }
	if($data['shipping_gateway']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Shipper': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['street_address'] = makeSafe($_REQUEST['street_address']);
		if($data['street_address'] == empty_lookup_value){ $data['street_address'] = ''; }
	if($data['street_address']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Street address': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['city'] = makeSafe($_REQUEST['city']);
		if($data['city'] == empty_lookup_value){ $data['city'] = ''; }
	if($data['city']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'City': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['state'] = makeSafe($_REQUEST['state']);
		if($data['state'] == empty_lookup_value){ $data['state'] = ''; }
	if($data['state']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'State': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['zip'] = makeSafe($_REQUEST['zip']);
		if($data['zip'] == empty_lookup_value){ $data['zip'] = ''; }
	if($data['zip']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Zip': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['country'] = makeSafe($_REQUEST['country']);
		if($data['country'] == empty_lookup_value){ $data['country'] = ''; }
	if($data['country']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Country': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['ship_width'] = makeSafe($_REQUEST['ship_width']);
		if($data['ship_width'] == empty_lookup_value){ $data['ship_width'] = ''; }
	$data['ship_length'] = makeSafe($_REQUEST['ship_length']);
		if($data['ship_length'] == empty_lookup_value){ $data['ship_length'] = ''; }
	$data['ship_height'] = makeSafe($_REQUEST['ship_height']);
		if($data['ship_height'] == empty_lookup_value){ $data['ship_height'] = ''; }
	$data['distance_unit'] = makeSafe($_REQUEST['distance_unit']);
		if($data['distance_unit'] == empty_lookup_value){ $data['distance_unit'] = ''; }
	$data['ship_weight'] = makeSafe($_REQUEST['ship_weight']);
		if($data['ship_weight'] == empty_lookup_value){ $data['ship_weight'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: shipping_before_update
	if(function_exists('shipping_before_update')){
		$args=array();
		if(!shipping_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `shipping` set       `register_id`=' . (($data['register_id'] !== '' && $data['register_id'] !== NULL) ? "'{$data['register_id']}'" : 'NULL') . ', `client_name`=' . (($data['client_name'] !== '' && $data['client_name'] !== NULL) ? "'{$data['client_name']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `company`=' . (($data['company'] !== '' && $data['company'] !== NULL) ? "'{$data['company']}'" : 'NULL') . ', `shipping_gateway`=' . (($data['shipping_gateway'] !== '' && $data['shipping_gateway'] !== NULL) ? "'{$data['shipping_gateway']}'" : 'NULL') . ', `street_address`=' . (($data['street_address'] !== '' && $data['street_address'] !== NULL) ? "'{$data['street_address']}'" : 'NULL') . ', `city`=' . (($data['city'] !== '' && $data['city'] !== NULL) ? "'{$data['city']}'" : 'NULL') . ', `state`=' . (($data['state'] !== '' && $data['state'] !== NULL) ? "'{$data['state']}'" : 'NULL') . ', `zip`=' . (($data['zip'] !== '' && $data['zip'] !== NULL) ? "'{$data['zip']}'" : 'NULL') . ', `country`=' . (($data['country'] !== '' && $data['country'] !== NULL) ? "'{$data['country']}'" : 'NULL') . ', `ship_width`=' . (($data['ship_width'] !== '' && $data['ship_width'] !== NULL) ? "'{$data['ship_width']}'" : 'NULL') . ', `ship_length`=' . (($data['ship_length'] !== '' && $data['ship_length'] !== NULL) ? "'{$data['ship_length']}'" : 'NULL') . ', `ship_height`=' . (($data['ship_height'] !== '' && $data['ship_height'] !== NULL) ? "'{$data['ship_height']}'" : 'NULL') . ', `distance_unit`=' . (($data['distance_unit'] !== '' && $data['distance_unit'] !== NULL) ? "'{$data['distance_unit']}'" : 'NULL') . ', `ship_weight`=' . (($data['ship_weight'] !== '' && $data['ship_weight'] !== NULL) ? "'{$data['ship_weight']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="shipping_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: shipping_after_update
	if(function_exists('shipping_after_update')){
		$res = sql("SELECT * FROM `shipping` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!shipping_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='shipping' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function shipping_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('shipping');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_register_id = thisOr(undo_magic_quotes($_REQUEST['filterer_register_id']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: register_id
	$combo_register_id = new DataCombo;
	// combobox: shipping_gateway
	$combo_shipping_gateway = new Combo;
	$combo_shipping_gateway->ListType = 0;
	$combo_shipping_gateway->MultipleSeparator = ', ';
	$combo_shipping_gateway->ListBoxHeight = 10;
	$combo_shipping_gateway->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/shipping.shipping_gateway.csv')){
		$shipping_gateway_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/shipping.shipping_gateway.csv')));
		$combo_shipping_gateway->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($shipping_gateway_data)));
		$combo_shipping_gateway->ListData = $combo_shipping_gateway->ListItem;
	}else{
		$combo_shipping_gateway->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("FedEx;;USPS;;Local Pickup")));
		$combo_shipping_gateway->ListData = $combo_shipping_gateway->ListItem;
	}
	$combo_shipping_gateway->SelectName = 'shipping_gateway';
	$combo_shipping_gateway->AllowNull = false;
	// combobox: distance_unit
	$combo_distance_unit = new Combo;
	$combo_distance_unit->ListType = 2;
	$combo_distance_unit->MultipleSeparator = ', ';
	$combo_distance_unit->ListBoxHeight = 10;
	$combo_distance_unit->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/shipping.distance_unit.csv')){
		$distance_unit_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/shipping.distance_unit.csv')));
		$combo_distance_unit->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($distance_unit_data)));
		$combo_distance_unit->ListData = $combo_distance_unit->ListItem;
	}else{
		$combo_distance_unit->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("in;;ft")));
		$combo_distance_unit->ListData = $combo_distance_unit->ListItem;
	}
	$combo_distance_unit->SelectName = 'distance_unit';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='shipping' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='shipping' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `shipping` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_register_id->SelectedData = $row['register_id'];
		$combo_shipping_gateway->SelectedData = $row['shipping_gateway'];
		$combo_distance_unit->SelectedData = $row['distance_unit'];
	}else{
		$combo_register_id->SelectedData = $filterer_register_id;
		$combo_shipping_gateway->SelectedText = ( $_REQUEST['FilterField'][1]=='7' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_distance_unit->SelectedText = ( $_REQUEST['FilterField'][1]=='16' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_register_id->HTML = '<span id="register_id-container' . $rnd1 . '"></span><input type="hidden" name="register_id" id="register_id' . $rnd1 . '" value="' . html_attr($combo_register_id->SelectedData) . '">';
	$combo_register_id->MatchText = '<span id="register_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="register_id" id="register_id' . $rnd1 . '" value="' . html_attr($combo_register_id->SelectedData) . '">';
	$combo_shipping_gateway->Render();
	$combo_distance_unit->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_register_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['register_id'] : $filterer_register_id); ?>"};

		jQuery(function() {
			if(typeof(register_id_reload__RAND__) == 'function') register_id_reload__RAND__();
		});
		function register_id_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#register_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_register_id__RAND__.value, t: 'shipping', f: 'register_id' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						$j('[name="register_id"]').val(resp.results[0].id);
						$j('[id=register_id-container-readonly__RAND__]').html('<span id="register_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }


						if(typeof(register_id_update_autofills__RAND__) == 'function') register_id_update_autofills__RAND__();
					});
				},
				width: ($j('fieldset .col-xs-11').width() - 99) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'shipping', f: 'register_id' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_register_id__RAND__.value = e.added.id;
				current_register_id__RAND__.text = e.added.text;
				$j('[name="register_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }


				if(typeof(register_id_update_autofills__RAND__) == 'function') register_id_update_autofills__RAND__();
			});

			if(!$j("#register_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: current_register_id__RAND__.value, t: 'shipping', f: 'register_id' }
				}).done(function(resp){
					$j('[name="register_id"]').val(resp.results[0].id);
					$j('[id=register_id-container-readonly__RAND__]').html('<span id="register_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }

					if(typeof(register_id_update_autofills__RAND__) == 'function') register_id_update_autofills__RAND__();
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_register_id__RAND__.value, t: 'shipping', f: 'register_id' }
			}).done(function(resp){
				$j('[id=register_id-container__RAND__], [id=register_id-container-readonly__RAND__]').html('<span id="register_id-match-text">' + resp.results[0].text + '</span>');
				if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=register_view_parent]').hide(); }else{ $j('.btn[id=register_view_parent]').show(); }

				if(typeof(register_id_update_autofills__RAND__) == 'function') register_id_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/shipping_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/shipping_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Shipping details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return shipping_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return shipping_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return shipping_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#register_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#register_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#email, #email-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#company').replaceWith('<div class=\"form-control-static\" id=\"company\">' + (jQuery('#company').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#shipping_gateway').replaceWith('<div class=\"form-control-static\" id=\"shipping_gateway\">' + (jQuery('#shipping_gateway').val() || '') + '</div>'); jQuery('#shipping_gateway-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#street_address').replaceWith('<div class=\"form-control-static\" id=\"street_address\">' + (jQuery('#street_address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#city').replaceWith('<div class=\"form-control-static\" id=\"city\">' + (jQuery('#city').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#state').replaceWith('<div class=\"form-control-static\" id=\"state\">' + (jQuery('#state').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#zip').replaceWith('<div class=\"form-control-static\" id=\"zip\">' + (jQuery('#zip').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#country').replaceWith('<div class=\"form-control-static\" id=\"country\">' + (jQuery('#country').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ship_width').replaceWith('<div class=\"form-control-static\" id=\"ship_width\">' + (jQuery('#ship_width').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ship_length').replaceWith('<div class=\"form-control-static\" id=\"ship_length\">' + (jQuery('#ship_length').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ship_height').replaceWith('<div class=\"form-control-static\" id=\"ship_height\">' + (jQuery('#ship_height').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('input[name=distance_unit]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=distance_unit]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#ship_weight').replaceWith('<div class=\"form-control-static\" id=\"ship_weight\">' + (jQuery('#ship_weight').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(register_id)%%>', $combo_register_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(register_id)%%>', $combo_register_id->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(register_id)%%>', urlencode($combo_register_id->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(shipping_gateway)%%>', $combo_shipping_gateway->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(shipping_gateway)%%>', $combo_shipping_gateway->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(distance_unit)%%>', $combo_distance_unit->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(distance_unit)%%>', $combo_distance_unit->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'register_id' => array('register', 'Register id'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(register_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(company)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(shipping_gateway)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(street_address)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(city)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(state)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(zip)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(country)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ship_width)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ship_length)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ship_height)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(distance_unit)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ship_weight)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ship_mass_unit)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(tracking_number)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(register_id)%%>', html_attr($row['register_id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(register_id)%%>', urlencode($urow['register_id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(company)%%>', html_attr($row['company']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(company)%%>', urlencode($urow['company']), $templateCode);
		$templateCode=str_replace('<%%VALUE(shipping_gateway)%%>', html_attr($row['shipping_gateway']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(shipping_gateway)%%>', urlencode($urow['shipping_gateway']), $templateCode);
		$templateCode=str_replace('<%%VALUE(street_address)%%>', html_attr($row['street_address']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(street_address)%%>', urlencode($urow['street_address']), $templateCode);
		$templateCode=str_replace('<%%VALUE(city)%%>', html_attr($row['city']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(city)%%>', urlencode($urow['city']), $templateCode);
		$templateCode=str_replace('<%%VALUE(state)%%>', html_attr($row['state']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(state)%%>', urlencode($urow['state']), $templateCode);
		$templateCode=str_replace('<%%VALUE(zip)%%>', html_attr($row['zip']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(zip)%%>', urlencode($urow['zip']), $templateCode);
		$templateCode=str_replace('<%%VALUE(country)%%>', html_attr($row['country']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(country)%%>', urlencode($urow['country']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_width)%%>', html_attr($row['ship_width']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_width)%%>', urlencode($urow['ship_width']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_length)%%>', html_attr($row['ship_length']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_length)%%>', urlencode($urow['ship_length']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_height)%%>', html_attr($row['ship_height']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_height)%%>', urlencode($urow['ship_height']), $templateCode);
		$templateCode=str_replace('<%%VALUE(distance_unit)%%>', html_attr($row['distance_unit']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(distance_unit)%%>', urlencode($urow['distance_unit']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_weight)%%>', html_attr($row['ship_weight']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_weight)%%>', urlencode($urow['ship_weight']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_mass_unit)%%>', html_attr($row['ship_mass_unit']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_mass_unit)%%>', urlencode($urow['ship_mass_unit']), $templateCode);
		$templateCode=str_replace('<%%VALUE(tracking_number)%%>', html_attr($row['tracking_number']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(tracking_number)%%>', urlencode($urow['tracking_number']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(register_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(register_id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(company)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(company)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(shipping_gateway)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(shipping_gateway)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(street_address)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(street_address)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(city)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(city)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(state)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(state)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(zip)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(zip)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(country)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(country)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_width)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_width)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_length)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_length)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_height)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_height)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(distance_unit)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(distance_unit)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_weight)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_weight)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ship_mass_unit)%%>', 'lb', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ship_mass_unit)%%>', urlencode('lb'), $templateCode);
		$templateCode=str_replace('<%%VALUE(tracking_number)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(tracking_number)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('emailEdit')){ document.getElementById('emailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode.="\tregister_id_update_autofills$rnd1 = function(){\n";
	$templateCode.="\t\tnew Ajax.Request(\n";
	if($dvprint){
		$templateCode.="\t\t\t'shipping_autofill.php?rnd1=$rnd1&mfk=register_id&id=' + encodeURIComponent('".addslashes($row['register_id'])."'),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get'}\n";
	}else{
		$templateCode.="\t\t\t'shipping_autofill.php?rnd1=$rnd1&mfk=register_id&id=' + encodeURIComponent(current_register_id{$rnd1}.value),\n";
		$templateCode.="\t\t\t{encoding: 'UTF-8', method: 'get', onCreate: function(){ \$j('#register_id$rnd1').prop('disabled', true); \$j('#register_idLoading').html('<img src=loading.gif align=top>'); }, onComplete: function(){".(($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#register_id$rnd1').prop('disabled', false); " : "\$j('#register_id$rnd1').prop('disabled', true); ")."\$j('#register_idLoading').html('');}}\n";
	}
	$templateCode.="\t\t);\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$j('#register_id_caption').length) \$j('#register_id_caption').click(function(){ register_id_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: shipping_dv
	if(function_exists('shipping_dv')){
		$args=array();
		shipping_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>