<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/shipping.php");
	include("$currDir/shipping_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('shipping');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "shipping";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`shipping`.`id`" => "id",
		"IF(    CHAR_LENGTH(`register1`.`id`) || CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`id`, ' - ', `register1`.`client_name`), '') /* Register id */" => "register_id",
		"IF(    CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`client_name`), '') /* Client name */" => "client_name",
		"IF(    CHAR_LENGTH(`register1`.`phone`), CONCAT_WS('',   `register1`.`phone`), '') /* Phone */" => "phone",
		"IF(    CHAR_LENGTH(`register1`.`email`), CONCAT_WS('',   `register1`.`email`), '') /* E-Mail */" => "email",
		"`shipping`.`company`" => "company",
		"`shipping`.`shipping_gateway`" => "shipping_gateway",
		"`shipping`.`street_address`" => "street_address",
		"`shipping`.`city`" => "city",
		"`shipping`.`state`" => "state",
		"`shipping`.`zip`" => "zip",
		"`shipping`.`country`" => "country",
		"`shipping`.`ship_width`" => "ship_width",
		"`shipping`.`ship_length`" => "ship_length",
		"`shipping`.`ship_height`" => "ship_height",
		"`shipping`.`distance_unit`" => "distance_unit",
		"`shipping`.`ship_weight`" => "ship_weight",
		"`shipping`.`ship_mass_unit`" => "ship_mass_unit",
		"`shipping`.`tracking_number`" => "tracking_number"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`shipping`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`shipping`.`id`" => "id",
		"IF(    CHAR_LENGTH(`register1`.`id`) || CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`id`, ' - ', `register1`.`client_name`), '') /* Register id */" => "register_id",
		"IF(    CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`client_name`), '') /* Client name */" => "client_name",
		"IF(    CHAR_LENGTH(`register1`.`phone`), CONCAT_WS('',   `register1`.`phone`), '') /* Phone */" => "phone",
		"IF(    CHAR_LENGTH(`register1`.`email`), CONCAT_WS('',   `register1`.`email`), '') /* E-Mail */" => "email",
		"`shipping`.`company`" => "company",
		"`shipping`.`shipping_gateway`" => "shipping_gateway",
		"`shipping`.`street_address`" => "street_address",
		"`shipping`.`city`" => "city",
		"`shipping`.`state`" => "state",
		"`shipping`.`zip`" => "zip",
		"`shipping`.`country`" => "country",
		"`shipping`.`ship_width`" => "ship_width",
		"`shipping`.`ship_length`" => "ship_length",
		"`shipping`.`ship_height`" => "ship_height",
		"`shipping`.`distance_unit`" => "distance_unit",
		"`shipping`.`ship_weight`" => "ship_weight",
		"`shipping`.`ship_mass_unit`" => "ship_mass_unit",
		"`shipping`.`tracking_number`" => "tracking_number"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`shipping`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`register1`.`id`) || CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`id`, ' - ', `register1`.`client_name`), '') /* Register id */" => "Register id",
		"IF(    CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`client_name`), '') /* Client name */" => "Client name",
		"IF(    CHAR_LENGTH(`register1`.`phone`), CONCAT_WS('',   `register1`.`phone`), '') /* Phone */" => "Phone",
		"IF(    CHAR_LENGTH(`register1`.`email`), CONCAT_WS('',   `register1`.`email`), '') /* E-Mail */" => "E-Mail",
		"`shipping`.`company`" => "Company",
		"`shipping`.`shipping_gateway`" => "Shipper",
		"`shipping`.`street_address`" => "Street address",
		"`shipping`.`city`" => "City",
		"`shipping`.`state`" => "State",
		"`shipping`.`zip`" => "Zip",
		"`shipping`.`country`" => "Country",
		"`shipping`.`ship_width`" => "Width",
		"`shipping`.`ship_length`" => "Length",
		"`shipping`.`ship_height`" => "Height",
		"`shipping`.`distance_unit`" => "Unit Measurement",
		"`shipping`.`ship_weight`" => "Ship weight",
		"`shipping`.`ship_mass_unit`" => "Mass unit",
		"`shipping`.`tracking_number`" => "Tracking number"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`shipping`.`id`" => "id",
		"IF(    CHAR_LENGTH(`register1`.`id`) || CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`id`, ' - ', `register1`.`client_name`), '') /* Register id */" => "register_id",
		"IF(    CHAR_LENGTH(`register1`.`client_name`), CONCAT_WS('',   `register1`.`client_name`), '') /* Client name */" => "client_name",
		"IF(    CHAR_LENGTH(`register1`.`phone`), CONCAT_WS('',   `register1`.`phone`), '') /* Phone */" => "phone",
		"IF(    CHAR_LENGTH(`register1`.`email`), CONCAT_WS('',   `register1`.`email`), '') /* E-Mail */" => "email",
		"`shipping`.`company`" => "company",
		"`shipping`.`shipping_gateway`" => "shipping_gateway",
		"`shipping`.`street_address`" => "street_address",
		"`shipping`.`city`" => "city",
		"`shipping`.`state`" => "state",
		"`shipping`.`zip`" => "zip",
		"`shipping`.`country`" => "country",
		"`shipping`.`ship_width`" => "ship_width",
		"`shipping`.`ship_length`" => "ship_length",
		"`shipping`.`ship_height`" => "ship_height",
		"`shipping`.`distance_unit`" => "distance_unit",
		"`shipping`.`ship_weight`" => "ship_weight",
		"`shipping`.`ship_mass_unit`" => "ship_mass_unit",
		"`shipping`.`tracking_number`" => "tracking_number"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'register_id' => 'Register id');

	$x->QueryFrom="`shipping` LEFT JOIN `register` as register1 ON `register1`.`id`=`shipping`.`register_id` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "shipping_view.php";
	$x->RedirectAfterInsert = "shipping_view.php?SelectedID=#ID#";
	$x->TableTitle = "Shipping";
	$x->TableIcon = "resources/table_icons/box_closed.png";
	$x->PrimaryKey = "`shipping`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Register id", "Client name", "Phone", "E-Mail", "Company", "Shipper", "Street address", "City", "State", "Zip", "Country", "Tracking number");
	$x->ColFieldName = array('register_id', 'client_name', 'phone', 'email', 'company', 'shipping_gateway', 'street_address', 'city', 'state', 'zip', 'country', 'tracking_number');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 19);

	$x->Template = 'templates/shipping_templateTV.html';
	$x->SelectedTemplate = 'templates/shipping_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `shipping`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='shipping' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `shipping`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='shipping' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`shipping`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: shipping_init
	$render=TRUE;
	if(function_exists('shipping_init')){
		$args=array();
		$render=shipping_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: shipping_header
	$headerCode='';
	if(function_exists('shipping_header')){
		$args=array();
		$headerCode=shipping_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: shipping_footer
	$footerCode='';
	if(function_exists('shipping_footer')){
		$args=array();
		$footerCode=shipping_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>